feat: added Forward Email (https://forwardemail.net), updated notes on Proton Mail, Tutanota, and Skiff
Lissy93/awesome-privacy pull request #201
Opened 2024-01-02 20:41 UTC by titanism

### Type

Addition

---

### Changes

We've added Forward Email (https://forwardemail.net) and updated accuracy of notes regarding "open source" claims for other providers.

---

### Supporting Material

See <https://github.com/Lissy93/email-comparison/pull/13> for supporting material and notes (similar PR to another repo owned by @Lissy93) 🙏.

---

### Affiliation

We are the creators and owners of the service.

---

### Checklist

- [x] I have read the [Contributing](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) guide, and confirmed my PR aligns with the requirements
- [x] I have performed a self-review (valid Markdown formatting, spelling, and grammar)
- [x] I have indicated whether I have any affiliation with any software / services added  
- [x] I agree to follow the repositories [Contributor Covenant Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

2024-01-02 20:53 UTC, Lissy93 requested changes
Unless I've misunderstood your service, shouldn't this be listed under [Mail Forwarding](https://github.com/Lissy93/awesome-privacy#anonymous-mail-forwarding), and not mail providers?

2024-01-02 20:53 UTC, Lissy93 commented on README.md
> +**[Forward Email](https://forwardemail.net)** | 100% open-source and privacy-focused encrypted email service that supports [SMTP](https://forwardemail.net/faq#do-you-support-sending-email-with-smtp),
> `[regex]()`

Missing link. (nice feature btw, haven't seen this on other email forwarders!)


> `It is compatible with Apple Mail, Gmail, Mozilla, Thunderbird, K-9 Mail, and any open-source email client.`

Just say what protocols it works with, this is unecissary. 


> `Unlike other email providers`

Reads like an advert. Let's keep things objective.

2024-01-02 20:53 UTC, Lissy93 commented on README.md
> +**[Tutanota](https://tutanota.com/)** | Free and open source ([front-end only](https://old.reddit.com/r/tutanota/comments/10hghin/tutanota_opens_backend_server_side/j5in1wp/)) email service based in
Changes to other entries should be made as a separate PR. Worried there's a bit of a conflict of interest otherwise.

2024-01-02 20:53 UTC, Lissy93 commented
Also I'm (slowly!) working my way through entries, updating them, but also shortening and them to be more factual and to-the-point. So could you make sure yours doesn't contain anything which reads too much like an ad.

2024-01-02 20:57 UTC, titanism commented on README.md
> +**[Tutanota](https://tutanota.com/)** | Free and open source ([front-end only](https://old.reddit.com/r/tutanota/comments/10hghin/tutanota_opens_backend_server_side/j5in1wp/)) email service based in
We're removing those from our commit now and will submit as separate PR's.

2024-01-02 20:57 UTC, titanism commented on README.md
> +**[Forward Email](https://forwardemail.net)** | 100% open-source and privacy-focused encrypted email service that supports [SMTP](https://forwardemail.net/faq#do-you-support-sending-email-with-smtp),
Will do.

2024-01-03 15:13 UTC, Lissy93 approved these changes

2024-01-03 15:13 UTC, merged